version: '3.1'

services:
  postgres:
    image: postgres:15-alpine
    restart: "always"
    environment:
      # Superuser username/password
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  redis:
    image: redis:7
    volumes:
      - "./redis-data:/data"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: "always"
    command: 'redis-server --save 60 1 --loglevel warning'