[api]
project_name= "Bot Prototype"
cors_origins= [ "*" ]

host="localhost"
port=8081

[telegram]
token='secret :^)'
webhook_base="your domain"
storage="redis"

[telegram.storage_args]
host="localhost"
port="6379"

[database]
dsn="postgresql+asyncpg://superuser:superpassword@localhost:5432/superuser"
